version: '3'

services:
  db:
    container_name: my-dbtest
    ports:
      - 54322:5432
    environment:
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASS}
    image: postgres:latest
    restart: unless-stopped

  pgadmin:
    container_name: pg-admintest
    ports:
      - 8080:8080
    environment:
      - PGADMIN_DEFAULT_EMAIL=${PGADMIN_EMAIL}
      - PGADMIN_DEFAULT_PASSWORD=${PGADMIN_PASSWORD}
    image: dpage/pgadmin4:latest

  myapp:
    container_name: my-apptest
    ports:
      - 1337:1337
    environment:
      - DATABASE_CLIENT=${D_CLIENT}
      - DATABASE_HOST=${D_HOST}
      - DATABASE_PORT=${D_PORT}
      - DATABASE_NAME=${D_NAME}
      - DATABASE_USERNAME=${D_USERNAME}
      - DATABASE_PASSWORD=${D_PASSWORD}
      - DATABASE_SSL=%{D_SSL}
    image: naskio/strapi:latest
